[package]
name = "cca"
version = "0.0.0"
edition = "2021"
author = ["The VirTEE Authors <virtee-security@redhat.com>"]
description = "Library for ARM CCA"
license = "Apache-2.0"
readme = "README.md"

[dependencies]
